# Twitter API connection configuration
TWITTER_API_REQUEST_METHOD = 'GET'
TWITTER_API_REQUEST_HOST = 'stream.twitter.com'
TWITTER_API_REQUEST_PORT = 443
TWITTER_API_REQUEST_PATH = '/1.1/statuses/filter.json'
TWEET_FILTER = 'track=football'

# OAuth Credentials
CONSUMER_KEY = 'TK2mTP3QNFaZ4XHIojyc5cOjf'
CONSUMER_SECRET = 'aWUMLnnNnxJVaOXFTWriTtmDXgs0kA4mPwVMyJ9ijDpqleT68Z'
ACCESS_TOKEN = '141120086-XmYaLGcVUItyJL4x537fWMgCi1G3PQrhO0hygFbL'
ACCESS_SECRET = 'RTsU9yV0OOsARMsdx719wCfHzfRDmJWpV9DoaaRauJott'